### ISSUE TITLE
Make `rimraf` and `gulp-symdest` dependencies instead of devDependencies

### ISSUE THREAD

**Issue by mathphreak** [joaomoreno/gulp-atom-electron#22]
Currently, `rimraf` and `gulp-symdest` are devDependencies in package.json. This means that they will not be installed by default when the package is installed as a dependency of another package. Since `index.js` `require()`s them, `gulp-atom-electron` crashes as soon as it is `require()`d.

**Comment by joaomoreno** [comment]
Many thanks!
