### ISSUE TITLE
Builds app but doesn't change anything from default

### ISSUE THREAD

**Issue by meetbryce** [joaomoreno/gulp-atom-electron#24]
![screenshot 2015-10-08 14 39 24](https://cloud.githubusercontent.com/assets/1845143/10357115/63690104-6dca-11e5-89d7-0b024743a6ec.png)

**Comment by joaomoreno** [comment]
Can you show me your gulpfile?

**Comment by meetbryce** [comment]
Thanks for following up.
Hosted it as a gist here -- https://gist.github.com/meetbryce/45d7fc71dae89071ae4e

On Thu, Oct 8, 2015 at 8:11 PM João Moreno <notifications@github.com> wrote:
Can you show me your gulpfile?

**Comment by joaomoreno** [comment]
And I assume there's a `src/package.json` file?

**Comment by joaomoreno** [comment]
Closing this, let me know if you can provide more details as to whether there is a `package.json` file and/or its contents.
