### ISSUE TITLE
FR: Please add support for  FreeBSD

### ISSUE THREAD

**Issue by mike-pt** [joaomoreno/gulp-atom-electron#27]
Please add FreeBSD as a supported platform.

**Comment by joaomoreno** [comment]
Do you mean you want FreeBSD support for [atom/electron](https://github.com/atom/electron)? Or does `gulp-atom-electron` really not work in FreeBSD? And if so, what errors do you see?

**Comment by joaomoreno** [comment]
Closing this as it appears you just want Electron in FreeBSD. Does the normal Linux Electron release work for you? If so, can't you use `linux` as the platform in `gulp-atom-electron`?

**Comment by mike-pt** [comment]
I was trying to build Microsoft vscode actually and it tries to build gulp-atom-eletron but fails cause there no release for FreeBSD, the interesting thing is that I can "npm install electron" (maybe its just using the linux version, I don't understand yet fully how npm or gulp works, probably need to read more on that, I guess when building it just uses github, and if there are not releases for a certain platform it will fail!?)

So as you say maybe this can work by setting the platfrom to "linux".

**Comment by joaomoreno** [comment]
Can you try downloading the latest [Electron release](https://github.com/atom/electron/releases) for Linux and see if it runs in your system?

**Comment by mike-pt** [comment]
I mean using the same source tree and see if it compiles here, direct ruining it won't work.

FreeBSD does have a Linux emulation layer and that might work, but I would need to go "Full linux".


In any case the issue is not with you're code indeed, but electron, I'll try to compile it and see what I get

**Comment by lapo-luchini** [comment]
This would be issue electron/electron#3797, I guess.
