### ISSUE TITLE
EISDIR: illegal operation on a directory, read

### ISSUE THREAD

**Issue by avanderhoorn** [joaomoreno/gulp-atom-electron#31]
I'm currently having some trouble getting the task up and running. It might be that I'm providing the wrong path to the scr, app structure or I have something else going on entirely. I'm still new to electron so it could be something totally noobish as well. Any thoughts?

Exception from build:
```
➜  electron-quick-start: gulp default
[20:48:19] Using gulpfile ~/Projects/electron-quick-start/gulpfile.js
[20:48:19] Starting 'default'...
events.js:154
      throw er; // Unhandled 'error' event
      ^
Error: EISDIR: illegal operation on a directory, read
    at Error (native)
```

Current gulp task:
```
var gulp = require('gulp');
var symdest = require('gulp-symdest');
var electron = require('gulp-atom-electron');
 
gulp.task('default', function () {
	return gulp.src(['./**/*', '!./build'])
		.pipe(electron({ version: '0.37.2', platform: 'darwin' }))
		.pipe(symdest('build'));
});
```

Directory structure post failed build:
<img width="229" alt="screen shot 2016-03-17 at 9 03 54 pm" src="https://cloud.githubusercontent.com/assets/585619/13868228/d3b20838-ec83-11e5-8e7d-ba3e49fa3c84.png">

**Comment by joaomoreno** [comment]
The use of `gulp.src` needs to be adjusted a bit, no need to use `.` in the paths. Also, when excluding the `build` folder, you should exclude everything within it, with a glob. So: `gulp.src(['**/*', '!build/**'])`.

Also, you can't run the `electron` task twice on top of the same folder. It's good practice to run a `clean` task before. So, here's something that works:

```
var gulp = require('gulp');
var symdest = require('gulp-symdest');
var electron = require('gulp-atom-electron');
var rimraf = require('rimraf');

gulp.task('clean', function (cb) {
	rimraf('build', cb);
});

gulp.task('default', ['clean'], function () {
    return gulp.src(['**/*', '!build/**'])
        .pipe(electron({ version: '0.37.2', platform: 'darwin' }))
        .pipe(symdest('build'));
});
```

Note that I've required `rimraf`, you need to add that as another dependency.

**Comment by jijiechen** [comment]
@avanderhoorn Did you solve the issue eventrally? How did you achieve it?
From build [script of Visual Studio Code](https://github.com/Microsoft/vscode/blob/047348a1f13f842c7135e83d28c32497ead90d2d/build/gulpfile.vscode.js#L166), it seems the gulp.src should accept a file instead a directory or a pattern.
