### ISSUE TITLE
Setting Application Menu removes it

### ISSUE THREAD

**Issue by sqwk** [joaomoreno/gulp-atom-electron#33]
Does `gulp-atom-electron`use `electron-prebuilt`? I am having trouble setting up a menubar from both the main process or the renderer process. When setting anymenubar using `Menu.setApplicationMenu()` (OSX) the menu disappears completely, also disabling the `⌘Q` shortcut

**Comment by joaomoreno** [comment]
It doesn't. It downloads the Electron builds straight from the github page.

This sounds more like a question to [Electron](https://github.com/atom/electron) itself.
