### ISSUE TITLE
it does... nothing?!

### ISSUE THREAD

**Issue by MartinMajewski** [joaomoreno/gulp-atom-electron#39]
Hi,

I run the example gulp configuration for building a darwin app, pointed to the right source and dest folder, but I only get:

>[11:11:41] Finished 'download-electron' after 36 s
[11:11:41] Starting 'build'...
bash-3.2$ 

and nothing... no error, no warning... nothing...

My gulp config is:

> gulp.task('default', function () {
        return gulp.src('./build/**')
        .pipe(electron({ version: '1.4.12', platform: 'darwin' }))
        .pipe(symdest('./app'));
});

Anything else to configure)?

Best wishes,
Martin

**Comment by willcalderbank** [comment]
I had the same problem, looks like it's because there is no package.json in the src

**Comment by joaomoreno** [comment]
Make sure there is a `package.json` in the src.
