### ISSUE TITLE
Request to Not Rely on GitHub Releases

### ISSUE THREAD

**Issue by wangweixuan** [joaomoreno/gulp-atom-electron#43]
Now we use GitHub Releases to download assets, which in my opinion is not to be relied on. It almost always fails in certain regions. Even if it can be accessed, the speed is extremely slow. This has made my experience of building VS Code full of pain.

So I suggest to provide alternative ways for downloading. Perhaps the default option is to download direct from `github.com/electron/electron/releases/download/...`. While I may specify a mirror in the environment variables, or as a download option. In that case the reliability of this package will be visibly increased.

**Comment by glachancecmaisonneuve** [comment]
So this was merged but shouldn't github-releases-ms be removed from package.json as well?  [Latest release (1.19.2)](https://github.com/joaomoreno/gulp-atom-electron/blob/0d6942b9375c52095ca2a403e155e391cb96c170/package.json#L29) did not remove the dependency and so the problem persists.

**Comment by joaomoreno** [comment]
Closing this as won't fix. Recommended way to depend on Electron can be found here: https://electronjs.org/docs/tutorial/first-app
