### ISSUE TITLE
Fails to with no error after updating packages

### ISSUE THREAD

**Issue by willcalderbank** [joaomoreno/gulp-atom-electron#50]
Hi,
Sorry that im unable to find the route cause but after hours of looking i'm hoping that someone will know the solution off the top of their head.

Everything was working fine until the beginning of the week, after running npm install a package must of updated, now gulp-atom-electron fails stopping gulp from running.

The resource/app file is created and my apps contents copies across then build stops (doesnt fail, just stops)

Any ideas?

Sorry again.

**Comment by willcalderbank** [comment]
After some more digging found the problem lies in the gulp-rename dependency, version 1.2.2 but the latest (released only 10 days ago) v1.2.3 doesn't seem to forward on the stream.

From package.json:
   "gulp-rename": "^1.2.0"

Allows gulp-rename to update, breaking gulp-atom-electron.

Including "gulp-rename": "1.2.2" in the applications package.json fixes the issue.

**Comment by joaomoreno** [comment]
Yup I could reproduce this. I will lock the dependency and release a patch version.

**Comment by joaomoreno** [comment]
Done: https://github.com/joaomoreno/gulp-atom-electron/commit/87f8a9dbcb80c3aea44347928ea9f9cda8868511

Released 1.17.1: https://www.npmjs.com/package/gulp-atom-electron
