### ISSUE TITLE
Why are vscode dates packaged incorrectly.

### ISSUE THREAD

**Issue by lichangwei123** [joaomoreno/gulp-atom-electron#78]
![img_v2_acc86b97-e190-48c9-9345-d02ab61baadg](https://user-images.githubusercontent.com/46671582/222704455-285fb91f-6257-479c-a1a5-652bc13a8ea0.png)
After packing, the date shows 1980.
![img_v2_7affb4c2-789b-4ced-9356-71d296ad0e9g](https://user-images.githubusercontent.com/46671582/222705079-43835fb5-04f4-4310-b5d3-3e3f32d5443b.png)

**Comment by joaomoreno** [comment]
Sorry, I no longer support this repository.
